on:
  push:
    branches:
      - master

name: Azure ARM

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:

    - uses: actions/checkout@main

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy resource group
      uses: azure/arm-deploy@v1
      with:
        scope: subscription
        region: northeurope
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        template: ./infra.bicep

    - name: Deploy common infra
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: rg-fnxr3ec3ms6mu
        template: ./common.bicep
        failOnStdErr: false
